adding role-variable for relayhost
geerlingguy/ansible-role-postfix pull request #14
Opened 2021-11-05 11:17 UTC by crazychatting

this change will allow you to also easily change the value for relayhost.

2022-02-07 14:39 UTC, crazychatting commented
Hello stale-bot,
please remove your stale label. This pull-request is still valid and I want @geerlingguy to review it.
Kind regards

2022-02-07 15:22 UTC, geerlingguy requested changes

2022-02-07 15:22 UTC, geerlingguy commented on defaults/main.yml
> +postfix_relayhost:
This should default to an empty `''` (string), to be explicit.

2022-02-07 15:22 UTC, geerlingguy commented on README.md
> +    postfix_relayhost: mailgw.example.com
The default listed in the README should match exactly the default that's in the `defaults/main.yml` file.

2022-02-07 15:22 UTC, geerlingguy commented on tasks/main.yml
> +      value: "{{ postfix_relayhost }}"
Is the setting `relayhost` okay to set without a value in the configuration? (e.g. as the default here), and is that the default for postfix out of the box? Just want to make sure if I push out a role update it doesn't break anyone's existing configuration.

2022-02-07 16:09 UTC, crazychatting commented on tasks/main.yml
> +      value: "{{ postfix_relayhost }}"
fair enough. I will check this. Thanks for the review!

2022-03-16 23:06 UTC, crazychatting commented on defaults/main.yml
> +postfix_relayhost:
done

2022-03-16 23:06 UTC, crazychatting commented on README.md
> +    postfix_relayhost: mailgw.example.com
done

2022-03-16 23:09 UTC, crazychatting commented on tasks/main.yml
> +      value: "{{ postfix_relayhost }}"
I tested this on a fresh install of postfix. This option is in the default main.cf uncommented and empty.

2022-06-19 00:47 UTC, crazychatting commented
PR is still active

2022-09-21 08:40 UTC, crazychatting commented
PR is still active

2022-10-29 03:55 UTC, closed without merging

2022-10-30 22:05 UTC, crazychatting commented
Hello stale-bot,
how can I reopen this PR? The PR is still valid.
Kind regards